<?php
	//connect to the database
	include 'connect.php';

	//initialize the variables
	$name = "";
	$password = "";
	$email = "";
	$usermail = "";

	//Upon POST request generated by the form
	if ($_SERVER["REQUEST_METHOD"] == "POST") {
		//Obtain the input from the user and normalize it
	  	$name = test_input($_POST["username"]);
	  	$password = test_input($_POST["password"]);
	 	$email = test_input($_POST["email"]);

	 	//if any of the fields are empty warn the user
	 	if($name == "" || $password == "" || $email == ""){
	 		echo "<script>alert('None of the required fields can be empty!')</script>";
			header("Refresh:0");
			exit;
	 	}

	 	//check if name or the email is already being used
	 	$sql = "SELECT * from User WHERE 1";
		$result = $conn->query($sql);
		if($result){
			//Iterate through each user
			while ($row = $result->fetch_assoc()) {
				//check if the name and email are already being used
				if($name == $row['username'] && $email == $row['email']){
  					echo "<script>alert('Username and Email are already being used. Choose different ones, or try logging in if you have already registered.')</script>";
					header("Refresh:0");
					exit;
				}
				//check if only the username is already being used
				else if($name == $row['username']){
  					echo "<script>alert('Username is already being used. Choose a different one, or try logging in if you have already registered.')</script>";
					header("Refresh:0");
					exit;
				}
				//check if only the email is already being used
				else if($email == $row['email']){
  					echo "<script>alert('Email is already being used. Choose a different one, or try logging in if you have already registered.')</script>";
					header("Refresh:0");
					exit;
				}
			}
		}

	 	//Register the user, assign the session id, and go to the home page;
	 	$sql = "INSERT INTO User(username, email, password) VALUES('$name', '$email', '$password')";
		$conn->query($sql);

		//Assign the Session id
		$sql = "SELECT ID from User WHERE username = '$name'";
		$result = $conn->query($sql);
		$row = $result->fetch_assoc();
		$_SESSION['userid'] = $row['ID'];
		header("Location:home.php");
		exit;
	}

	function test_input($data) {
	  $data = trim($data);
	  $data = stripslashes($data);
	  $data = htmlspecialchars($data);
	  return $data;
	}
?>

<!-- HTML FILE -->
<!doctype html>
<html>
	<head>
		<meta charset="utf-8">
		<title>Untitled Document</title>
	</head>

	<body>
		<h1>We Are Glad That You Decided To Join Our Community! </h1>
		<form method="POST">
		  	<label for="username">Username:</label>
		  	<input type="text" name="username" id="username">
		  	<label for="email">Email:</label>
		 	<input type="email" name="email" id="email">
		  	<label for="password">Password:</label>
		  	<input type="password" name="password" id="password">
		  	<input type="submit" name="submit" id="submit" value="Lets Go!">
		</form>
	</body>
</html>
