<?php
	//connect to the database
	include 'connect.php';

	//initialize the variables
	$name = "";
	$password = "";
	$email = "";
	$usermail = "";

	//Upon POST request generated by the form
	if ($_SERVER["REQUEST_METHOD"] == "POST") {
		//Obtain the input from the user and normalize it
	  	$name = test_input($_POST["username"]);
	  	$password = test_input($_POST["password"]);
	 	$email = test_input($_POST["email"]);

	 	//if any of the fields are empty warn the user
	 	if($name == "" || $password == "" || $email == ""){
	 		echo "<script>alert('None of the required fields can be empty!')</script>";
			header("Refresh:0");
			exit;
	 	}

	 	//check if name or the email is already being used
	 	$sql = "SELECT * from User WHERE 1";
		$result = $conn->query($sql);
		if($result){
			//Iterate through each user
			while ($row = $result->fetch_assoc()) {
				//check if the name and email are already being used
				if($name == $row['username'] && $email == $row['email']){
  					echo "<script>alert('Username and Email are already being used. Choose different ones, or try logging in if you have already registered.')</script>";
					header("Refresh:0");
					exit;
				}
				//check if only the username is already being used
				else if($name == $row['username']){
  					echo "<script>alert('Username is already being used. Choose a different one, or try logging in if you have already registered.')</script>";
					header("Refresh:0");
					exit;
				}
				//check if only the email is already being used
				else if($email == $row['email']){
  					echo "<script>alert('Email is already being used. Choose a different one, or try logging in if you have already registered.')</script>";
					header("Refresh:0");
					exit;
				}
			}
		}

	 	//Register the user, assign the session id, and go to the home page;
	 	$sql = "INSERT INTO User(username, email, password) VALUES('$name', '$email', '$password')";
		$conn->query($sql);

		//Assign the Session id
		$sql = "SELECT ID from User WHERE username = '$name'";
		$result = $conn->query($sql);
		$row = $result->fetch_assoc();
		$_SESSION['userid'] = $row['ID'];
		header("Location:home.php");
		exit;
	}

	function test_input($data) {
	  $data = trim($data);
	  $data = stripslashes($data);
	  $data = htmlspecialchars($data);
	  return $data;
	}
?>

<!-- HTML FILE -->
<!doctype html>
<html>
	<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Untitled Document</title>
	<link href="css/bootstrap.css" rel="stylesheet" type="text/css">
	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
	</head>

	<body>
		<h1>We Are Glad That You Decided To Join Our Community! </h1>
		<div class="container-fluid" align="center">
			<form method="POST">
				<div class="row" style="margin-top:20px;">
					<div class="form-group">	   
						<div class="col-sm-3 col-sm-offset-1">
							<label for="username" >Username:</label>							
							<input type="text" name="username" id="username">
						</div>
					</div>
				</div>

				<div class="row" style="margin-top:20px;">
					<div class="form-group">	   
						<div class="col-sm-3 col-sm-offset-1">
							<label for="email">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Email:</label>
							<input type="email" name="email" id="email">
						</div>
					</div>
				</div>

				<div class="row" style="margin-top:20px;">
					<div class="form-group">	   
						<div class="col-sm-3 col-sm-offset-1">
							<label for="password">Password:</label>
							<input type="password" name="password" id="password">
						</div>
					</div>
				</div>

				<div class="row" style="margin-top:20px;">
					<div class="form-group">	   
						<div class="col-sm-3 col-sm-offset-1">
							<input type="submit" name="submit" id="submit" value="Lets Go!">
						</div>
					</div>
				</div>
      		</form>							
		</div>
	</body>
</html>
